# Generated by Django 5.1 on 2025-05-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
