# Generated by Django 5.2.1 on 2025-05-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_github_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_links',
        ),
        migrations.CreateModel(
            name='GitHubLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_links', to='projects.project')),
            ],
        ),
    ]
