# Generated by Django 5.2.1 on 2025-05-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_github_links_githublink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githublink',
            old_name='product',
            new_name='project',
        ),
    ]
